### PR TITLE
Sc 97 add systematic to logo

### PR DESCRIPTION
**Pull request by Cromski**

### CODE REVIEW

**Review by jfho — COMMENTED** [review]
Seems ok, tests are failing though? Also, do we want the Systematic logo to use the Systematic font?

**Comment by DanyalYor** [comment]
There are some conflicts that need to be resolved. `git pull origin development` should do it.

**Review by DanyalYor — CHANGES_REQUESTED** [review]
There are some conflicts that need to be resolved. git pull origin development should do it.

**Review by DanyalYor — APPROVED** [review]
lgtm!

**Pull request merged**
