### PR TITLE
Sc 93 home page

### PR DESCRIPTION
**Pull request by adamjhr**

### CODE REVIEW

**Review by Spobendonis — DISMISSED** [review]
Looks good, though the commit messages were a little vague. It was hard to get the idea of the changes from them. Otherwise great work! <3

**Review by jfho — COMMENTED** [review]
image
the percentages seem to not be contained within the boxes?

**Comment by AstralEik** [comment]
As is commented above, the %% numbers break/look bad on screensizes wider than 1800~~ pixels.
This is not on par with our responsiveness goal, so it has to be fixed.

**Review by jfho — APPROVED** [review]
Looks good, we might change how often we update the percentages eventually but seems out of scope for this :)

**Pull request merged**
